### ISSUE TITLE
Missing or invalid options error after yesterday's update

### ISSUE THREAD

**Issue by pjatx** [tmslnz/gulp-shopify-theme#6]
Hey there, 

I'm getting the following error in v1.0.15.

```
[18:21:27] Finished 'watch' after 33 ms
[18:21:27] 'theme:init' errored after 33 ms
[18:21:27] Error: Missing or invalid options
    at new Shopify (/Users/philipjohnson/projects/store-test/node_modules/shopify-api-node/index.js:36:11)
    at ShopifyTheme.makeConfig (/Users/philipjohnson/projects/store-test/node_modules/gulp-shopify-theme/index.js:97:24)
    at ShopifyTheme.init (/Users/philipjohnson/projects/store-test/node_modules/gulp-shopify-theme/index.js:82:14)
    at gulp.task.done (/Users/philipjohnson/projects/store-test/gulp/tasks/deploy.js:24:27)
    at taskWrapper (/Users/philipjohnson/projects/store-test/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at asyncRunner (/Users/philipjohnson/projects/store-test/node_modules/async-done/index.js:39:18)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[18:21:27] 'serve' errored after 34 ms
[18:21:27] 'default' errored after 2.7 s
[18:21:27] The following tasks did not complete: browser-sync, theme:watch
[18:21:27] Did you forget to signal async completion?
```

Went back to 1.0.14 and the error goes away.

Using the repo below:

https://github.com/Pixel2HTML/shopify-skeleton/issues/5

**Comment by tmslnz** [comment]
Thank you for reporting. This was due to a breaking change in the `shopify-api-node` module `options` argument.

**Comment by pjatx** [comment]
No problem! Thanks for maintaining.

**Comment by shelldandy** [comment]
@tmslnz so what's the solution here? do we need to change something in our end? 😮

**Comment by tmslnz** [comment]
No, it’s backwards compatible with the old options format.

**Comment by shelldandy** [comment]
awesome thanks a lot!
